
-- local mct = get_mct()

-- local mct_mod = mct:register_mod("mct_demo")

-- local test = mct_mod:add_new_radio_button(
--     "test",
--     "Testing Radio Button",
--     "Testing Tooltip",
--     {
--         {
--             key = "test_1",
--             text = "Test 1",
--         },
--         {
--             key = "test_2",
--             text = "Test 2",
--         },
--         {
--             key = "test_3",
--             text = "Test 3",
--         },
--     },
--     "test_2"
-- )

-- local dummy = mct_mod:add_new_option("dummy", "checkbox")
-- dummy:set_text("Dummy")

-- ---@type MCT.Option.Dropdown
-- local test = mct_mod:add_new_option("test_dropdown", "dropdown")
-- test:add_dropdown_values({
--     {
--         key = "one",
--         text = "mct_ui_mods_header",
--     },
--     {
--         key = "two",
--         text = "mct_ui_settings_title",
--     },
--     {
--         key = "three",
--         text = "mct_button_client_change",
--     },
--     {
--         key = "four",
--         text = "four",
--     },
--     {
--         key = "five",
--         text = "five",
--     },
--     {
--         key = "six",
--         text = "six",
--     },
--     {
--         key = "seven",
--         text = "seven",
--     },
--     {
--         key = "eight",
--         text = "eight",
--     },
--     {
--         key = "nine",
--         text = "nine",
--     },
--     {
--         key = "ten",
--         text = "ten",
--     },
--     {
--         key = "eleven",
--         text = "eleven",
--     },
-- })

-- -- -- local s = mct_mod:add_new_option("testing_slider", "slider"):slider_set_precision(2):set_default_value(50):slider_set_min_max(0, 100):set_text("Testing Slider")

-- -- -- mct_mod:add_new_option("test_b", 'checkbox'):set_text("Testing Checkbox")